#include "colors.h"
#include <stdint.h>

#define NUM_OF_TYPES 7//tetromino types

#define WORLD_WIDTH 10
#define WORLD_HEIGHT 22 
#define TETROMINO_WIDTH 4
#define TETROMINO_HEIGHT 4

typedef uint32_t cell; // left 16 bit = visible?, right 16 bit = color, use macros below

#define VISIBLE(c) (c&0xFFFF0000)
#define COLOR(c) (c&0x0000FFFF)
#define MAKE_VISIBLE(c) (c|0x0001FFFF)
#define MAKE_INVISIBLE(c) (c&0x0000FFFF)//same as color for now

typedef struct{
	int points;
	cell field[WORLD_WIDTH][WORLD_HEIGHT];
} world;

typedef struct{
	int x,y;
	cell field[TETROMINO_WIDTH][TETROMINO_HEIGHT];
} tetromino;



int go_down(tetromino * t, world * w);
int go_left(tetromino * t, world * w);
int go_right(tetromino * t, world * w);

//type range: 0-6 (7 tetrominos)
tetromino * create_tetromino(int type, int x, int y);


//FIELDS for tetrominos
//static: dont tell linker, use only here
//extern: tell linker for others to use, define array in .c file!

static const cell t_L[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_VISIBLE(YELLOW),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(YELLOW),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(YELLOW),	MAKE_VISIBLE(YELLOW),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_J[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_INVISIBLE(1),		MAKE_VISIBLE(BLUE),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_VISIBLE(BLUE),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(BLUE),	MAKE_VISIBLE(BLUE),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_Z[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_INVISIBLE(1),		MAKE_VISIBLE(GREEN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(GREEN),	MAKE_VISIBLE(GREEN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(GREEN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_S[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_VISIBLE(RED),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(RED),		MAKE_VISIBLE(RED),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_VISIBLE(RED),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_I[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_VISIBLE(CYAN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(CYAN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(CYAN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(CYAN),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_O[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_VISIBLE(WHITE),	MAKE_VISIBLE(WHITE),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_VISIBLE(WHITE),	MAKE_VISIBLE(WHITE),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};

static const cell t_T[TETROMINO_WIDTH][TETROMINO_HEIGHT] = {
{MAKE_VISIBLE(MAGENTA),	MAKE_VISIBLE(MAGENTA),	MAKE_VISIBLE(MAGENTA),	MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_VISIBLE(MAGENTA),	MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)},
{MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1),		MAKE_INVISIBLE(1)}
};
